### ISSUE TITLE
Anyone else getting this issue?

### ISSUE THREAD

**Issue by infinitylabs** [iwdmb/GetLineApiAuthToken#2]
Enter PinCode '6550' to your mobile phone in 2 minutes
Q5LzSsxzjJ7UNeN0gm0VWlIB3gCq****
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/GetLineApiAuthToken/__main__.py", line 14, in <module>
    authToken = GetLineAuthToken(username, password);
  File "/root/GetLineApiAuthToken/**main**.py", line 7, in GetLineAuthToken
    return LineClient(username, password).authToken;
  File "GetLineApiAuthToken/line/client.py", line 318, in **init**
    self.login()
  File "GetLineApiAuthToken/line/client.py", line 382, in login
    if msg.type == 1:
AttributeError: 'int' object has no attribute 'type'

**Comment by iwdmb** [comment]
Please give me **msg** variable value.

edit client.py, line 380

```
msg = self._client.loginWithVerifierForCertificate(self.verifier)
# Add the following line
print "\n\n{0}\n\n".format(msg)
```

```
~# python GetLineApiAuthToken
```

**Comment by infinitylabs** [comment]
msg always returns an int value of 1.

The error originally happened on my older custom linebot, so I found your version in hopes of a fix but it produces the same result. Im just curious if anyone else experienced this. 

It could just be an account issue, but I tried 4 different accounts on 4 different IP's and all returned int 1...

**Comment by iwdmb** [comment]
sorry, I have not come across this problem
but, **msg** correct return results:

```
LoginResult(authToken='XXX', verifier=None, type=1, pinCode=None, certificate='XXX')


<class 'curve.ttypes.LoginResult'>
```

good, luck!
